### ISSUE TITLE
"Cree" or "CREE"?

### ISSUE THREAD

**Issue by evanshultz** [KiCad/LEDs.pretty#38]
All but one footprint use all capital letters. One is mixed case. It seems Cree's website uses mixed case:
![image](https://user-images.githubusercontent.com/1936989/27503785-c4836c8a-5834-11e7-8abe-d4e33951083a.png)

Any objections if I change it all to mixed case?

**Comment by SchrodingersGat** [comment]
None from me. Digikey lists them as Cree for example

**Comment by evanshultz** [comment]
Sounds good. PR submitted at https://github.com/KiCad/LEDs.pretty/pull/39.
