### ISSUE TITLE
RFC: Color for new 3D models 

### ISSUE THREAD

**Issue by Shackmeister** [KiCad/LEDs.pretty#44]
Hey 
Im in the process of making some new models for the SMD chip Leds (0402) since Im scripting them it wouldnt be a problem to generate a lot of the color variations of standard Leds. Only question if it would be bloating the library since a footprint for each would be needed. Also in case it would be approved, how should the naming scheme be?

**Comment by SchrodingersGat** [comment]
I don't want to go *too far* down the path of prioritizing eye-candy over functional mechanical models. At the end of the day KiCad is an engineering tool (although pretty renders are always well appreciated).

1. These variants are only for .wrl files, I assume?
2. How large is a typical SMD LED model?
3. Naming (if approved) should be e.g. `LED_0402_Red`
4. There still should be a generic `LED_0402` model - what color will you choose for that?

**Comment by Shackmeister** [comment]
1. the script does generally export both step and WRL, it would probably be a bit tricky to have the footprint point to a different Step model
2. did a quick test, this 0603_Concave.WR (see below)L is 23.1kb, the step/WRL pair is 104kb. for the 0603_Convex.WRL the size is  20,7kb while the pair is 99,2kb
3. sound good
4. I would probably go with a transparent white, a lot of LEDS have that color even when its a colored LED
![0603_leds](https://user-images.githubusercontent.com/5279723/28859233-7e1d3514-7756-11e7-8739-be258d7c07f8.png)
![0603_led_convex](https://user-images.githubusercontent.com/5279723/28859242-8777dd6c-7756-11e7-9d8d-4dfd40f733e3.png)
![led_0603_concave](https://user-images.githubusercontent.com/5279723/28859246-8b7b86f2-7756-11e7-90b2-fe6749a463ab.png)

**Comment by Shackmeister** [comment]
@SchrodingersGat too much eye-candy? :P
![led_0603](https://user-images.githubusercontent.com/5279723/28883712-a9251dd6-77af-11e7-9834-123b9d247a49.png)

**Comment by SchrodingersGat** [comment]
MY EYES! THEY ARE FULL OF CANDY!

As pretty as this is, I would be wary of putting in too much detail. It's only going to add rendering time (and  memory requirements). While not an issue for an individual LED, if this is extended to a board with hundreds of components, it could become an issue.

**Comment by Shackmeister** [comment]
I should hopefully have time tomorrow to add the new models, I think Ill add the generic color models and without the internal parts. In case somebody would like models with different colors you can just let me know :)

**Comment by poeschlr** [comment]
@Shackmeister are all your questions answered? If so please close this as i declare this repo as legacy. (This conversation would anyways fit better into the packages3d repo.)
